### ISSUE TITLE
InvokeTelephonyIntegrationAPI is returning Error on executeOmniFlow Method

### ISSUE THREAD

**Issue by magg99** [service-cloud-voice/examples-from-doc#15]
We are using Sample_SCV_Inbound_Subflow to execute OmniChannel flow designed in Salesforce. Our SF Flow is working fine when we are passing values while Debugging but when we are trying to trigger SF Omni channel flow from InvokeTelephonyIntegrationAPI Lambda Function, it is returning an error. We are passing key-value pairs in Lambda Function as shown in the Screenshots attached with this issue
![Execute Omniflow 1](https://user-images.githubusercontent.com/82077076/143075644-405148b7-6853-4da9-be40-8e2c9c28aa00.PNG)
![Execute Omniflow 2](https://user-images.githubusercontent.com/82077076/143075699-fc11619e-f651-4e07-b92f-9d6ab54d0485.PNG)

.

**Comment by jinalkathiara** [comment]
That depends on the Omniflow you defined at the Salesforce side. Looking at the screenshot, I couldn't find anything erroneous at your end. Can you share omni flow here to get the idea what could be wrong. Also any error description would also be helpful.

**Comment by magg99** [comment]
Hi Jinal. Thanks for writing back. Following are the Snapshots for Salesforce Flow that we have created:
![Salesforce Flow](https://user-images.githubusercontent.com/82077076/143394502-715c1264-148a-4721-bfd0-c6432a619051.PNG)
![Salesforce Flow 2](https://user-images.githubusercontent.com/82077076/143394525-fadcd7ab-f990-4c78-ab1c-158108db7059.PNG)

**Comment by jinalkathiara** [comment]
@magg99 Can we close this issue ? and post your resolution too. Is Salesforce documentation was helpful?

**Comment by magg99** [comment]
@jinalkathiara Yes you can close this issue for now.
