### ISSUE TITLE
Not Working for Call back Queue

### ISSUE THREAD

**Issue by magg99** [service-cloud-voice/examples-from-doc#17]
We were able to make it work for other Queues in Service Cloud Voice but now we are facing another issue where we are not able to make it work for Call back Queue. We are not able to retain the Call back Number in Call back Queue using these Contact Flows and Omni Channel Flow. Can you please suggest some solution on that?

**Comment by jinalkathiara** [comment]
@magg99 Did you check this [help](https://developer.salesforce.com/docs/atlas.en-us.voice_developer_guide.meta/voice_developer_guide/voice_example_queued_callback.htm) ? 

This should be able to guide you on how to work with the Callback queue?

**Comment by magg99** [comment]
Yes @jinalkathiara, We have already implemented this but we are using Omni Channel flow for Voice(Pilot) to get the Live Call View in Salesforce's Omni Supervisor Tab. We were able to make it work for all other queues except for Callback Queue where we are not able to retain the number in that particular queue unless an Agent Responds to it. That Callback gets vanished from Omni Supervisor Tab as soon as the call is disconnected. So, can you please suggest some solution for that?

**Comment by jinalkathiara** [comment]
@magg99 i discussed this with the team. Omni flow routing for service cloud voice can work with all the queues except callback queue. This is a missed from the public documentation. We will update the help documents to list this as a known limitation.

**Comment by jinalkathiara** [comment]
Closing this issue.
