### ISSUE TITLE
Import Failure - Sample_SCV_Transfer_with_Omni_Channel_Flow

### ISSUE THREAD

**Issue by greg-amato** [service-cloud-voice/examples-from-doc#25]
Updating example Contact Flows after v9.1 release and all of them worked except for 'Sample_SCV_Transfer_with_Omni_Channel_Flow'

1. Creating new Contact Flow
2. Import flow (beta)
3. Receive Error: 'Failed to import contact flow.The imported file cannot be read.'

**Comment by naadev** [comment]
Same for Sample_SCV_Agent_Whisper_With_Transcription which is required for Sample_SCV_Outbound_Flow_With_Transcription

**Comment by jinalkathiara** [comment]
Before you import, make sure that you select create transfer flow and only then you can import that flow. 
Look at this document - https://docs.aws.amazon.com/connect/latest/adminguide/contact-initiation-methods.html
Make sure that the flow you are mentioning is a type of agent transfer flow.

**Comment by jinalkathiara** [comment]
Closing this issue.
